version: 2
updates:
- package-ecosystem: "ruby:bundler"
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 10
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 10
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope